#!/bin/bash

####Notes & Comments####
help() {
echo ""
echo "Convert Dicom to NIFTI"
echo "Daniel Elbich"
echo "Cogntive, Aging, and Neurogimaging Lab"
echo "Created: 6/4/19"
echo ""
echo ""
echo "Usage:"
echo "sh dicom2niibatch --subj <subjectIDs>"
echo ""
echo ""
echo " Loops through subject folders and converts raw DICOM images to NIFTI."
echo " Requires dcm2niix packaged with MRIcroGL (https://github.com/"
echo " rordenlab/dcm2niix)."
echo ""
echo "Required arguments:"
echo ""
echo "	    --subj          <single ID or multiple ID text file>"
echo ""
echo ""
exit 1
}
[ "$1" = "--help" ] && help

#Arguement check
POSITIONAL=()
while [[ $# -gt 0 ]]
do
key="$1"

case $key in

--subj) subjList="$2"
shift # past argument
shift # past value
;;
*)    # unknown option
POSITIONAL+=("$1") # save it in an array for later
shift # past argument
;;
esac
done
set -- "${POSITIONAL[@]}" # restore positional parameters

###Read Subject IDs###
if [[ -f $subjList ]]; then
	i=0
	while read -r LINE || [[ -n $LINE ]]; do
		subs[i]=$LINE
		let "i++"
	done < $subjList
else
	subs=$subjList
fi

###Setup###
dcm2niipath='/path/to/folder/with/dcm2niix/program'
projectDir=/path/to/parent/folder
mkdir -p $dataDir/NIIDATA

for ((i=0; i<${#subs[@]}; i++))
do

subject=${subs[i]}

##Make output folders##
mkdir -p $projectDir/NIIDATA/"sub-"$subject/anat
mkdir -p $projectDir/NIIDATA/"sub-"$subject/func

##Set File Paths##
dataset1=$dataDir/RAWDATA/$subject/FOLDERNAME
dataset2=$dataDir/RAWDATA/$subject/FOLDERNAME

##Convert to NIFTI with BIDS Compliant Naming##
$dcm2niipath/dcm2niix -z i -f "sub-"$subject"_T1w" -o $dataDir/data/"sub-"$subject/anat $dataset1
$dcm2niipath/dcm2niix -z i -f "sub-"$subject"_task-TASKNAME1_bold" -o $dataDir/data/"sub-"$subject/func $dataset2


done



